name: location_provider_flutter
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  location: ^5.0.3
  signalr_netcore: ^1.4.3
  flutter_dotenv: ^5.1.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - .env.production
